=
[PHP]=
;;;;;;auto_prepend_file = '/home/mafwor5/public_html/wordfence-waf.php'
=
display_errors = Off
max_execution_time =300
max_input_vars = 3000
memory_limit = 256M
post_max_size = 128M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php82"
upload_max_filesize =512M
zlib.output_compression = Off
auto_prepend_file = '/home/mafwor5/public_html/wordfence-waf.php'
